# Generated by Django 3.1 on 2022-02-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20220214_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
